[package]
name = "rust_todo"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4.41", features = ["serde"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
dotenv = "0.15.0"